<?php
declare(strict_types=1);
namespace Kuko\Tests\Integration;
use Kuko\Db;
use Kuko\MediaRepo;
use PHPUnit\Framework\TestCase;

final class MediaRepoTest extends TestCase
{
    private Db $db;
    private string $dir;
    private MediaRepo $repo;

    protected function setUp(): void
    {
        $this->db = Db::fromDsn('sqlite::memory:');
        $this->db->exec("CREATE TABLE gallery_photos (
            id INTEGER PRIMARY KEY AUTOINCREMENT, filename TEXT NOT NULL, webp TEXT,
            alt_text TEXT NOT NULL, sort_order INTEGER NOT NULL DEFAULT 0,
            is_visible INTEGER NOT NULL DEFAULT 1, uploaded_at TEXT NOT NULL DEFAULT (datetime('now')))");
        $this->dir = sys_get_temp_dir() . '/kuko-media-' . uniqid();
        mkdir($this->dir, 0777, true);
        $this->repo = new MediaRepo($this->db, $this->dir);
    }

    protected function tearDown(): void
    {
        foreach (glob($this->dir . '/*') ?: [] as $f) @unlink($f);
        @rmdir($this->dir);
    }

    private function fakeUpload(): array
    {
        // Valid PNG generated by GD itself: PHP 8.5's strict libpng rejects
        // hand-crafted minimal PNGs, so use a fixture GD can actually decode.
        $png = base64_decode('iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAFElEQVQImWPkEpFjgAEmBiSAmwMADKgARK9yomwAAAAASUVORK5CYII=');
        $tmp = tempnam(sys_get_temp_dir(), 'up');
        file_put_contents($tmp, $png);
        return ['name' => 'test.png', 'type' => 'image/png', 'tmp_name' => $tmp, 'error' => 0, 'size' => strlen($png)];
    }

    public function testUploadInsertsRow(): void
    {
        $row = $this->repo->upload($this->fakeUpload(), 'Alt text');
        $this->assertGreaterThan(0, $row['id']);
        $this->assertSame('Alt text', $row['alt_text']);
        $this->assertFileExists($this->dir . '/' . $row['filename']);
    }

    public function testListVisibleOrdersBySort(): void
    {
        $a = $this->repo->upload($this->fakeUpload(), 'A');
        $b = $this->repo->upload($this->fakeUpload(), 'B');
        $this->repo->reorder([$b['id'], $a['id']]);
        $list = $this->repo->listVisible();
        $this->assertSame($b['id'], $list[0]['id']);
    }

    public function testSetVisibilityHides(): void
    {
        $a = $this->repo->upload($this->fakeUpload(), 'A');
        $this->repo->setVisibility($a['id'], false);
        $this->assertCount(0, $this->repo->listVisible());
        $this->assertCount(1, $this->repo->listAll());
    }

    public function testDeleteRemovesRowAndFile(): void
    {
        $a = $this->repo->upload($this->fakeUpload(), 'A');
        $path = $this->dir . '/' . $a['filename'];
        $this->assertFileExists($path);
        $this->repo->delete($a['id']);
        $this->assertCount(0, $this->repo->listAll());
        $this->assertFileDoesNotExist($path);
    }

    public function testRejectsNonImage(): void
    {
        $tmp = tempnam(sys_get_temp_dir(), 'up');
        file_put_contents($tmp, 'not an image');
        $this->expectException(\RuntimeException::class);
        $this->repo->upload(['name' => 'x.txt', 'type' => 'text/plain', 'tmp_name' => $tmp, 'error' => 0, 'size' => 12], 'A');
    }

    public function testUpdateAlt(): void
    {
        $a = $this->repo->upload($this->fakeUpload(), 'Old');
        $this->repo->updateAlt($a['id'], 'New alt');
        $this->assertSame('New alt', $this->repo->listAll()[0]['alt_text']);
    }

    public function testUploadGeneratesWebpVariant(): void
    {
        $row = $this->repo->upload($this->fakeUpload(), 'A');
        $this->assertNotNull($row['webp']);
        $this->assertFileExists($this->dir . '/' . $row['webp']);
    }
}
